// 广告banner列表
export const SUCCESS_GET_AD_LIST = 'SUCCESS_GET_AD_LIST'
export const FAILURE_GET_AD_LIST = 'FAILURE_GET_AD_LIST'

// 中奖名单公告
export const SUCCESS_GET_ANNOUNCE_LIST = 'SUCCESS_GET_ANNOUNCE_LIST'
export const FAILURE_GET_ANNOUNCE_LIST = 'FAILURE_GET_ANNOUNCE_LIST'

// 商品列表
export const SUCCESS_GET_GOODS_LIST = 'SUCCESS_GET_GOODS_LIST'
export const SUCCESS_GET_GOODS_ADD_LIST = 'SUCCESS_GET_GOODS_ADD_LIST'
export const REQUEST_GOODS_LIST = 'REQUEST_GOODS_LIST'
export const FAILURE_GET_GOODS_LIST = 'FAILURE_GET_GOODS_LIST'

// 商品详情
export const SUCCESS_GET_GOODS_DETAIL = 'SUCCESS_GET_GOODS_DETAIL'
export const FAILURE_GET_GOODS_DETAIL = 'FAILURE_GET_GOODS_DETAIL'

// 购物清单详情
export const SUCCESS_GET_CART_DETAIL = 'SUCCESS_GET_CART_DETAIL'
export const FAILURE_GET_CART_DETAIL = 'FAILURE_GET_CART_DETAIL'

// 购物清单详情
export const SUCCESS_GET_USER_CONSUME_MONEY = 'SUCCESS_GET_USER_CONSUME_MONEY'
export const FAILURE_GET_USER_CONSUME_MONEY = 'FAILURE_GET_USER_CONSUME_MONEY'

// 商品参与者列表
export const SUCCESS_GET_GOODS_JOINER = 'SUCCESS_GET_GOODS_JOINER'
export const SUCCESS_GET_GOODS_ADD_JOINER = 'SUCCESS_GET_GOODS_ADD_JOINER'
export const REQUEST_GOODS_JOINER = 'REQUEST_GOODS_JOINER'
export const FAILURE_GET_GOODS_JOINER = 'FAILURE_GET_GOODS_JOINER'

// 商品参与者信息
export const SUCCESS_GET_GOODS_USER = 'SUCCESS_GET_GOODS_USER'
export const FAILURE_GET_GOODS_USER = 'FAILURE_GET_GOODS_USER'

// 商品图文详情
export const SUCCESS_GET_GOODS_PIC_DETAIL = 'SUCCESS_GET_GOODS_PIC_DETAIL'
export const FAILURE_GET_GOODS_PIC_DETAIL = 'FAILURE_GET_GOODS_PIC_DETAIL'

// 商品往期揭晓
export const SUCCESS_GET_GOODS_PAST = 'SUCCESS_GET_GOODS_PAST'
export const SUCCESS_GET_GOODS_ADD_PAST = 'SUCCESS_GET_GOODS_ADD_PAST'
export const REQUEST_GOODS_PAST = 'REQUEST_GOODS_PAST'
export const FAILURE_GET_GOODS_PAST = 'FAILURE_GET_GOODS_PAST'