// 广告banner列表
export const SUCCESS_GET_AD_LIST = 'SUCCESS_GET_AD_LIST'
export const FAILURE_GET_AD_LIST = 'FAILURE_GET_AD_LIST'

// 中奖名单公告
export const SUCCESS_GET_ANNOUNCE_LIST = 'SUCCESS_GET_ANNOUNCE_LIST'
export const FAILURE_GET_ANNOUNCE_LIST = 'FAILURE_GET_ANNOUNCE_LIST'

// 商品列表
export const SUCCESS_GET_GOODS_LIST = 'SUCCESS_GET_GOODS_LIST'
export const FAILURE_GET_GOODS_LIST = 'FAILURE_GET_GOODS_LIST'