export const SUCCESS_GET_DEMO_LIST = 'SUCCESS_GET_DEMO_LIST'
export const FAILURE_GET_DEMO_LIST = 'FAILURE_GET_DEMO_LIST'
// 获取type
export const SUCCESS_GET_TYPE_LIST = 'SUCCESS_GET_TYPE_LIST'
export const FAILURE_GET_TYPE_LIST = 'FAILURE_GET_TYPE_LIST'

// 获取商品列表
export const SUCCESS_GET_GOODS_LIST = 'SUCCESS_GET_GOODS_LIST'
export const FAILURE_GET_GOODS_LIST = 'FAILURE_GET_GOODS_LIST'

// Loading State

export const CHANGE_LOADING = 'CHANGE_LOADING'

// 充值记录
export const SUCCESS_GET_RECHARGE_RECORD_LIST='SUCCESS_GET_RECHARGE_RECORD_LIST';
export const FAILURE_GET_RECHARGE_RECORD_LIST='FAILURE_GET_RECHARGE_RECORD_LIST';

// 夺宝记录
export const SUCCESS_GET_SNARCH_RECORD_LIST='SUCCESS_GET_SNARCH_RECORD_LIST';
export const FAILURE_GET_SNARCH_RECORD_LIST='FAILURE_GET_SNARCH_RECORD_LIST';

// 地址列表
export const SUCCESS_GET_ADDRESS_LIST='SUCCESS_GET_ADDRESS_LIST';
export const FAILURE_GET_ADDRESS_LIST='FAILURE_GET_ADDRESS_LIST';

// 地址列表
export const SUCCESS_GET_DETAIL_LIST='SUCCESS_GET_DETAIL_LIST';
export const FAILURE_GET_DETAIL_LIST='FAILURE_GET_DETAIL_LIST';

// 地址列表
export const SUCCESS_GET_AREA_LIST='SUCCESS_GET_AREA_LIST';
export const FAILURE_GET_AREA_LIST='FAILURE_GET_AREA_LIST';