// 广告banner列表
export const SUCCESS_GET_AD_LIST = 'SUCCESS_GET_AD_LIST'
export const FAILURE_GET_AD_LIST = 'FAILURE_GET_AD_LIST'

// 中奖名单公告
export const SUCCESS_GET_ANNOUNCE_LIST = 'SUCCESS_GET_ANNOUNCE_LIST'
export const FAILURE_GET_ANNOUNCE_LIST = 'FAILURE_GET_ANNOUNCE_LIST'

// 商品列表
export const SUCCESS_GET_GOODS_LIST = 'SUCCESS_GET_GOODS_LIST'
export const FAILURE_GET_GOODS_LIST = 'FAILURE_GET_GOODS_LIST'

// 商品详情
export const SUCCESS_GET_GOODS_DETAIL = 'SUCCESS_GET_GOODS_DETAIL'
export const FAILURE_GET_GOODS_DETAIL = 'FAILURE_GET_GOODS_DETAIL'

// 商品参与者列表
export const SUCCESS_GET_GOODS_JOINER = 'SUCCESS_GET_GOODS_JOINER'
export const FAILURE_GET_GOODS_JOINER = 'FAILURE_GET_GOODS_JOINER'

// 商品参与者信息
export const SUCCESS_GET_GOODS_USER = 'SUCCESS_GET_GOODS_USER'
export const FAILURE_GET_GOODS_USER = 'FAILURE_GET_GOODS_USER'