// 广告banner列表
export const SUCCESS_GET_SHARE_LIST = 'SUCCESS_GET_SHARE_LIST'
export const FAILURE_GET_SHARE_LIST = 'FAILURE_GET_SHARE_LIST'
export const SUCCESS_GET_SHARE_ADD_LIST = 'SUCCESS_GET_SHARE_ADD_LIST'

